
package org.codefagsystem;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FagsystemService", targetNamespace = "http://codefagsystem.org/", wsdlLocation = "http://localhost:8089/Fagsystem/ws/fagsystem?wsdl")
public class FagsystemService
    extends Service
{

    private final static URL FAGSYSTEMSERVICE_WSDL_LOCATION;
    private final static WebServiceException FAGSYSTEMSERVICE_EXCEPTION;
    private final static QName FAGSYSTEMSERVICE_QNAME = new QName("http://codefagsystem.org/", "FagsystemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/Fagsystem/ws/fagsystem?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FAGSYSTEMSERVICE_WSDL_LOCATION = url;
        FAGSYSTEMSERVICE_EXCEPTION = e;
    }

    public FagsystemService() {
        super(__getWsdlLocation(), FAGSYSTEMSERVICE_QNAME);
    }

    public FagsystemService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FAGSYSTEMSERVICE_QNAME, features);
    }

    public FagsystemService(URL wsdlLocation) {
        super(wsdlLocation, FAGSYSTEMSERVICE_QNAME);
    }

    public FagsystemService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FAGSYSTEMSERVICE_QNAME, features);
    }

    public FagsystemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FagsystemService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Fagsystem
     */
    @WebEndpoint(name = "FagsystemPort")
    public Fagsystem getFagsystemPort() {
        return super.getPort(new QName("http://codefagsystem.org/", "FagsystemPort"), Fagsystem.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Fagsystem
     */
    @WebEndpoint(name = "FagsystemPort")
    public Fagsystem getFagsystemPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://codefagsystem.org/", "FagsystemPort"), Fagsystem.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FAGSYSTEMSERVICE_EXCEPTION!= null) {
            throw FAGSYSTEMSERVICE_EXCEPTION;
        }
        return FAGSYSTEMSERVICE_WSDL_LOCATION;
    }

}
