
package org.codefagsystem;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Fagsystem", targetNamespace = "http://codefagsystem.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Fagsystem {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://codefagsystem.org/Fagsystem/createContractRequest", output = "http://codefagsystem.org/Fagsystem/createContractResponse")
    public String createContract(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://codefagsystem.org/Fagsystem/createCustomerRequest", output = "http://codefagsystem.org/Fagsystem/createCustomerResponse")
    public String createCustomer(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://codefagsystem.org/Fagsystem/generateUniqueNrRequest", output = "http://codefagsystem.org/Fagsystem/generateUniqueNrResponse")
    public String generateUniqueNr(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://codefagsystem.org/Fagsystem/updateContractStatusRequest", output = "http://codefagsystem.org/Fagsystem/updateContractStatusResponse")
    public String updateContractStatus(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
